export const UsersData = [
  {
    id: "1",
    name: "Leanne Graham",
    userName: "Bret",
    jobTitle: 'developer',
    joinDate: '01/01/2020',
    group_name: 'group A',
    task_id: '',
    task_title: 'task 1',
    task_description:'This is your first task',
    task_duration:'22/03/2022 - 24/03/2022',
    task_status: "In Progress",
    duration: '',
    task_created_date: '',
    group_created_date: '01/03/2022',
        user_task: {
            task_id: '',
            task_title: '',
            task_description:'',
            task_duration:'',
            task_status: '',
            created_date: '',
          
        },
        User_group: {
            qroup_id: '1',
            group_name: 'group A',
            created_date: '01/03/2022',
        },
  },
  {
  id: "2",
  name: "ali",
  userName: "ALi Ahmed",
  jobTitle: 'Hr',
  joinDate: '01/01/2020',
  group_name: 'group B',
  task_id: '',
  task_title: 'task 2',
  task_description:'This is your second task',
  task_duration:'22/03/2022 - 24/03/2022',
  task_status: 'Open',
  duration: '',
  task_created_date: '',
  group_created_date: '01/03/2022',
      user_task: {
          task_id: '',
          task_title: '',
          task_description:'',
          task_duration:'',
          task_status: '',
          created_date: '',
      },
      User_group: {
          qroup_id: '',
          group_name: '',
          created_date: '',
      },
},
];
